---
title: "Task 2 Analysis"
author: "Harry Williams"
date: "10/11/2020"
output: 
  html_document:
    df_print: paged
    toc: yes
    toc_float: yes
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages 
```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(here)
```

## Data
```{r, message=FALSE}
cake_ingredients <- read_csv(here("clean_data/cake_ingredients.CSV"))
```
## Q1 -Which cake has the most cocoa in it?

```{r}
cake_ingredients %>%
  filter(ingredient == "cocoa") %>%
  slice_max(quantity)
```

## Q2 - For sponge cake, how many cups of ingredients are used in total?
```{r, message=FALSE}
cake_ingredients %>%
  filter(cake == "sponge", measure == "cup") %>%
  group_by(cake) %>%
  summarise(total_cups = sum(quantity))
```

## Q3 How many ingredients are measured in teaspoons?
```{r}
cake_ingredients %>%
  filter(measure == "teaspoon") %>%
  distinct(ingredient) %>%
  summarise(number_of_ingredients_using_teaspoons = n())
```

## Q4 Which cake has the most unique ingredients? 
```{r, message=FALSE}
cake_ingredients %>%
  group_by(ingredient) %>%
  mutate(count = n()) %>% # find how many times each ingredient is used
  ungroup() %>%
  filter(count == 1) %>%
  group_by(cake) %>%
  summarise(number_of_unique_ingredients = n())
```

Alternatively if the question is asking how many ingredients 

```{r, message=FALSE}
cake_ingredients %>%
  group_by(cake) %>%
  summarise(number_of_ingredients = n()) %>%
  slice_max(number_of_ingredients)
```


## 5 Which ingredients are used only once?
```{r , message=FALSE}
cake_ingredients %>%
  group_by(ingredient) %>%
  summarise(number_of_times_used = n()) %>%
  filter(number_of_times_used == 1)
```
